import { Metadata } from "next";

export const metadata : Metadata = {
    title: {
        default: "Next.js Tutorial - Codevolution",
        template:"%s | Codevolution",
        absolute: ""
    },
    description: "Generated by Next.js",
}

export default function RootLayout({ 
    children 
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <header style={{
                        backgroundColor: "lightblue",
                        padding:"1rem"
                    }}>
                        <p>Header</p>
                </header>

                {/* This is where the page content will be rendered */}
                {children}

                <footer 
                    style={{
                        backgroundColor: "ghostwhite",
                        padding:"1rem"
                    }}
                >
                    <p>Footer</p>
                </footer>
            </body>
        </html>
    )
}