import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
    absolute: "",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/*
        min-h-screen + flex-col makes the body at least as tall as the viewport.
        The <main> gets flex-1 so it grows to fill leftover space, which pushes
        the footer to the bottom even when a page has little content.
      */}
      <body className="flex min-h-screen flex-col bg-slate-50 text-slate-900 antialiased">
        <Header />

        <main className="mx-auto w-full max-w-5xl flex-1 px-4 py-8">
          <ErrorWrapper>{children}</ErrorWrapper>
        </main>

        <Footer />
      </body>
    </html>
  );
}
